# [Choice] Ruby version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.1, 3.0, 2, 2.7, 2.6, 3-bullseye, 3.1-bullseye, 3.0-bullseye, 2-bullseye, 2.7-bullseye, 2.6-bullseye, 3-buster, 3.1-buster, 3.0-buster, 2-buster, 2.7-buster, 2.6-buster
ARG VARIANT=3
FROM mcr.microsoft.com/devcontainers/ruby:${VARIANT}

# Ensure we're running the latest bundler, as what ships with the Ruby image may not be current
RUN gem install bundler
