let { task, desc } = require('jake');

const fs = require('fs');

desc('This is the default task.');
task('setup', function () {
  fs.copyFile('.env.sample', '.env', fs.constants.COPYFILE_EXCL, (err) => { if (err) console.log(err) })
  console.log('Copied .env.sample to .env')
});
